pipeline {
    
    agent any
    
    stages {
        
        stage('Build') {
            steps {
                sh 'echo $PATH'
                sh 'docker run hello-world'
            }
        }
        
    }
}
