pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'hello-world'
                }
            }
            steps {
                //sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        
    }
}
